app/urls.py
from django.contrib import admin
from django.urls import path, include

API_PREFIX = "api/v1"

urlpatterns = [
    # UI
    path("admin/", admin.site.urls),
    path("news_board/", include("news_board.urls")),
    # API
    path(f"{API_PREFIX}/news_board/", include("news_board.api.urls")),
]

news_board/api/urls.py
from django.urls import path

from news_board.api.views import (
    NewsListCreateView,
    CommentListCreateView,
    CommentUpdateDeleteView,
    NewsUpdateDeleteView,
    VoteUpdateView,
)


app_name = "api_news_board"

urlpatterns = [
    # news:
    path("news/", NewsListCreateView.as_view(), name="news_list"),
    path("news/<int:pk>/", NewsUpdateDeleteView.as_view(), name="news_update"),
    path("news/<int:pk>/upvotes/", VoteUpdateView.as_view(), name="news_vote"),
    # comments:
    path(
        "news/<int:pk>/comments/", CommentListCreateView.as_view(), name="comments_list"
    ),
    path(
        "news/<int:pk>/comments/<int:comment_pk>/",
        CommentUpdateDeleteView.as_view(),
        name="comment_update_delete",
    ),
]

news_board/urls.py
from django.urls import path
from .views import CommentCreateView, Index, to_vote

app_name = "news_board"

urlpatterns = [
    path("", Index.as_view(), name="index"),
    path("comment_create/<int:pk>", CommentCreateView.as_view(), name="comment_create"),
    path("to_vote/<int:pk>", to_vote, name="to_vote"),
]

news_board/models.py
from django.db import models


class BaseModel(models.Model):
    class Meta:
        abstract = True

    create_date = models.DateTimeField(null=True, auto_now_add=True)


class News(BaseModel):
    title = models.CharField(max_length=256, null=False, blank=False)
    link = models.URLField(
        max_length=256,
        null=False,
        blank=False,
    )
    amount_of_upvotes = models.SmallIntegerField(default=0)
    author_name = models.CharField(
        max_length=128, null=False, blank=False, default="unknown author"
    )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = "News"
        ordering = ["-amount_of_upvotes", "create_date"]


class Comment(BaseModel):
    news = models.ForeignKey(to=News, on_delete=models.CASCADE, related_name="comments")
    comment_author_name = models.CharField(
        max_length=128, null=False, blank=False, default="unknown user"
    )
    text = models.TextField(max_length=512, null=False, blank=False)

    def __str__(self):
        return self.text

news_board/forms.py
from .models import News, Comment
from django import forms
from django.forms import ModelForm


class CommentForm(ModelForm):
    news = forms.ModelChoiceField(queryset=News.objects.all())

    class Meta:
        model = Comment
        fields = ["text", "comment_author_name", "news"]

news_board/api/views.py
from rest_framework import generics

from rest_framework.generics import get_object_or_404

from news_board.api.serializers import NewsVoutesSerializer


from news_board.api.serializers import NewsSerializer, CommentSerializer
from news_board.models import News, Comment


class NewsListCreateView(generics.ListCreateAPIView):
    queryset = News.objects.all()
    serializer_class = NewsSerializer


class VoteUpdateView(generics.RetrieveUpdateAPIView):
    queryset = News.objects.all()
    serializer_class = NewsVoutesSerializer

    def put(self, request, *args, **kwargs):
        news = News.objects.get(id=self.kwargs["pk"])
        news.amount_of_upvotes += 1
        news.save()
        return super().put(request, *args, **kwargs)

    def patch(self, request, *args, **kwargs):
        return self.put(request, *args, **kwargs)


class NewsUpdateDeleteView(generics.RetrieveUpdateDestroyAPIView):
    queryset = News.objects.all()
    serializer_class = NewsSerializer


class CommentListCreateView(generics.ListCreateAPIView):
    serializer_class = CommentSerializer

    def get_queryset(self):
        queryset = Comment.objects.filter(news=self.kwargs["pk"])
        return queryset


class CommentUpdateDeleteView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Comment.objects.all()
    serializer_class = CommentSerializer

    def get_object(self):
        queryset = self.get_queryset()
        news_id = self.kwargs.get("pk")
        comment_id = self.kwargs.get("comment_pk")
        return get_object_or_404(queryset, news__id=news_id, id=comment_id)

news_board/views.py
from django.shortcuts import redirect

from .models import News, Comment
from .forms import CommentForm
from django.views.generic import CreateView, ListView
from django.urls import reverse_lazy


class Index(ListView):
    model = News
    context_object_name = "news_list"
    template_name = "index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["news"] = News.objects.all()
        context["comments"] = Comment.objects.all()
        return context


class CommentCreateView(CreateView):
    model = Comment
    form_class = CommentForm
    success_url = reverse_lazy("news_board:index")
    template_name = "create_comment.html"
    context_object_name = "comment"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["news"] = News.objects.get(id=self.kwargs["pk"])
        return context

    def post(self, request, *args, **kwargs):
        request.POST._mutable = True
        request.POST["news"] = self.kwargs["pk"]
        request.POST._mutable = False
        return super().post(request, *args, **kwargs)


def to_vote(request, pk):
    result = News.objects.get(id=pk)
    result.amount_of_upvotes += 1
    result.save()
    return redirect("news_board:index")

news_board/templates/base_template.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
          integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

{% block title%}
<title>NEWS</title>
{% endblock %}

<style>

table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}
</style>

</head>


<body>

{%url 'news_board:index' as List %}


<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
      <a class="navbar-brand">News board</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
        </ul>
            <ul class="navbar-nav ">

                <li class="nav-item {% if request.path == List %} active {% endif %}">
                    <a class="nav-link" href="{% url 'news_board:index' %}">News</a>
                </li>
            </ul>
      </div>
    </div>
</nav>


<div class="container">
    <div class="border border-white rounded-pill shadow p-3 mb-5 mt-5 bg-white rounded text-center">
        {% block header %}
            <h3>Welcome</h3>
        {% endblock %}
    </div>

    {% block content %}
    {% endblock %}

</div>
</body>
</html>

news_board/templates/create_comment.html
{% extends 'base_template.html' %}
{% load crispy_forms_tags %}

{% block title%}
<title>Create comment</title>
{% endblock %}

{% block header %}
<h3>Create comment for {{ news }}</h3>
{% endblock %}


{% block content %}
    <form method="post">

        {% csrf_token %}

        <h5>Text:</h5>
        {{form.text}}<br>

        <h5>Author name:</h5>
        {{form.comment_author_name}}<br>

        {{ form.news.as_hidden }}<br>

        <button type="submit" class="btn btn-success">Add comment</button><br>
    </form>
{% endblock %}

news_board/templates/index.html
{% extends 'base_template.html' %}


{% block content %}

    {% for some_news in news_list %}
        <div>
            <br>
            <h5><a href="{{some_news.link}}">{{some_news}}</a> (<a href="{{some_news.link}}">{{some_news.link}}</a> )</h5>
            by {{some_news.author_name}} | {{some_news.create_date}} | amount of upvotes: {{some_news.amount_of_upvotes}}

            <form method="post" action="{% url 'news_board:to_vote' some_news.id %}">{% csrf_token %}
                <button class="btn btn-info">Vote</button><br> </form>

            <h3>Comments:</h3>
            {% for comment in comments %}
                {% if comment.news_id == some_news.id %}
                    <div style="border: 3px solid #fff;">
                        <b>{{comment}}</b><br>
                        <b>from: {{comment.comment_author_name}}</b>; <b>date: {{comment.create_date}}</b>
                    </div>
                {% endif %}
            {% endfor %}
            <p><a href="{% url 'news_board:comment_create' some_news.id %}">Add comment</a></p>
        </div>
    {% endfor %}

{% endblock %}